//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillDtl
    {
        public int id { get; set; }
        public string name { get; set; }
        public string toc { get; set; }
        public string prerequisites { get; set; }
        public Nullable<int> fees { get; set; }
    }
}
